/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        primary: '#006c49',
        'primary-container': '#10b981',
        'on-primary': '#ffffff',
        'on-primary-container': '#00422b',
        secondary: '#575e70',
        'secondary-container': '#d9dff5',
        'on-secondary': '#ffffff',
        'on-secondary-container': '#5c6274',
        tertiary: '#a43a3a',
        'tertiary-container': '#fc7c78',
        'on-tertiary': '#ffffff',
        background: '#f9f9ff',
        surface: '#f9f9ff',
        'surface-variant': '#dce2f3',
        'surface-container': '#e7eefe',
        'surface-container-low': '#f0f3ff',
        'surface-container-high': '#e2e8f8',
        'surface-container-highest': '#dce2f3',
        'surface-container-lowest': '#ffffff',
        'on-surface': '#151c27',
        'on-surface-variant': '#3c4a42',
        outline: '#6c7a71',
        'outline-variant': '#bbcabf',
        'inverse-surface': '#2a313d',
        'inverse-on-surface': '#ebf1ff',
        'inverse-primary': '#4edea3',
        error: '#ba1a1a',
        'error-container': '#ffdad6',
        'on-error': '#ffffff',
        'on-error-container': '#93000a',
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
        display: ['Hanken Grotesk', 'sans-serif'],
        mono: ['Geist Mono', 'monospace'],
      },
    },
  },
  plugins: [],
}
